title: Jasim Chouhan
description: Mobile Application & backend Developer
site_title: '@jasim - Jasim Chouhan'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: jasim92
blog_url: https://www.nagekar.com
email: jasim.chouhan@yahoo.com
keybase_username: jasim
twitter_username: jasim92
reddit_username: ristedaar

# absolute or relative
profile_picture: assets/images/jasim.jpg

# Google Analytics ID
google_analytics: 