title: Jasim Chouhan
description: Mobile Application & backend Developer
site_title: '@jasim - Jasim Chouhan'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: jasim92
email: jasim.chouhan@yahoo.com
keybase_username: jasim
twitter_username: jasim92
reddit_username: ristedaar
stackverflow_username: users/13718810/jasim-chouhan
linkedin_username: jasim-chouhan-898a6b55

# absolute or relative
profile_picture: assets/images/jasim.jpg
cv: assets/cv/cv.pdf

# Google Analytics ID
google_analytics: 